
package tetris5;

import java.io.*;
import java.awt.event.*;
public class Main extends javax.swing.JFrame {

    boolean flag=false;
    public Main() {
        initComponents();
        
     this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setEditable(false);
        t1.setBackground(new java.awt.Color(0, 0, 0));
        t1.setColumns(20);
        t1.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setRows(5);
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
       
        int keyCode = evt.getKeyCode();
        String key=KeyEvent.getKeyText(keyCode);
        println(key);
       
        
        if(flag==false && keyCode>49)
	{keyCode++;}
        
        if(keyCode==49)
        {
           
       new tetris_frame5('n').setVisible(true);
        this.dispose();
        }
        else if(keyCode==50)
        {
            
         new tetris_frame5('l').setVisible(true);   
         this.dispose();
        }
        else if(keyCode==51)
        {     
        this.dispose();
        }
        else
        {
        println("Enter valid choice ");
        }    
	
        
       
    }//GEN-LAST:event_t1KeyPressed


void startGame()
{
	File f1=new File("board.txt");
        File f2=new File("stack.txt");
        
        if(f1.exists() && f2.exists() )
        {flag=true;
        }
        else
        {flag=false;}
        
	int i=1,n;
        t1.setText("");
	println("Tetris Game");
	println(i+". New Game");
	i++;
	if(flag)
	{println(i+". Load Game");
	i++;
	}
	println(i+". Exit Game");
	println("Enter your choice ");
	
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Main().startGame();
             
            }
        });
    }
   
    public void print(String s)
  {
      t1.append(s);
  }
  
  public void println(String s)
  {
      t1.append(s+"\n");
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
